# Generated by Django 6.0 on 2025-12-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_college_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[("job", "Job"), ("internship", "Internship")],
                        default="job",
                        max_length=20,
                    ),
                ),
                (
                    "companies",
                    models.CharField(
                        help_text="Example: Amazon • Google • Startups", max_length=300
                    ),
                ),
                ("eligibility", models.CharField(max_length=200)),
                (
                    "package",
                    models.CharField(
                        help_text="Example: ₹6–30 LPA or ₹15k/month", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("upcoming", "Upcoming"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide from students"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
