# Generated by Django 6.0 on 2025-12-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="university",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
