# Generated by Django 6.0 on 2025-12-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_studentprofile_university_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="branch",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="career_goal",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="college",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="education",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="track",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="year",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
