# Generated by Django 4.2.16 on 2025-12-27 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_studentprofile_is_profile_complete_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContextMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("career_goal", models.CharField(blank=True, max_length=200)),
                ("branch", models.CharField(blank=True, max_length=100)),
                ("education_level", models.CharField(blank=True, max_length=100)),
                ("target_roles", models.CharField(blank=True, max_length=200)),
                ("skills", models.TextField(blank=True)),
                ("weak_areas", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
