from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
import textwrap
import os

OUT_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'docs')
os.makedirs(OUT_PATH, exist_ok=True)
OUT_FILE = os.path.join(OUT_PATH, 'AI_features.pdf')

def draw_paragraph(c, text, x, y, wrap_width=95, leading=14):
    for line in textwrap.wrap(text or '', width=wrap_width):
        c.drawString(x, y, line)
        y -= leading
        if y < inch:
            c.showPage()
            y = A4[1] - inch
    return y

def build_features_pdf():
    c = canvas.Canvas(OUT_FILE, pagesize=A4)
    width, height = A4
    x = inch
    y = height - inch

    c.setFont("Helvetica-Bold", 18)
    c.drawString(x, y, "CareerInnTech — AI Interview Features")
    y -= 0.4 * inch

    c.setFont("Helvetica-Bold", 12)
    c.drawString(x, y, "Core Product Features")
    y -= 0.25 * inch
    c.setFont("Helvetica", 10)

    features = [
        "Adaptive AI-driven question generation using LLM prompts",
        "Server-side speech-to-text transcription (Whisper)",
        "Text-to-speech playback with browser TTS fallback",
        "Automatic recording with silence detection and answer capture",
        "Live speech analytics: WPM, filler-word count, clarity and pacing",
        "Camera analytics: face presence, engagement, away detection and gaze warnings",
        "Hint system and text-only question view for accessibility",
        "Skip, extend, and code-editor drawer controls",
        "Per-question feedback generated by LLM, merged into QA pairs",
        "Robust matching and fallbacks to ensure feedback for every question",
        "Downloadable PDF report with question-wise answers and analytics",
        "Session storage for interview metadata and transcripts",
        "Configurable interview settings: role, stack, difficulty, focus distribution",
        "Open architecture (Django) allowing LLM/prompt customization and integrations"
    ]

    for idx, f in enumerate(features, start=1):
        y = draw_paragraph(c, f"{idx}. {f}", x+6, y, wrap_width=100)
        y -= 4

    y -= 0.2 * inch
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(x, y, "Generated from the project's AI interview code (services, views, frontend scripts).")

    c.showPage()
    c.save()
    print("Features PDF written to:", OUT_FILE)

if __name__ == '__main__':
    build_features_pdf()
