# Generated by Django 6.0 on 2025-12-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BranchVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science"),
                            ("ece", "Electronics & Communication"),
                            ("eee", "Electrical Engineering"),
                            ("mech", "Mechanical Engineering"),
                            ("civil", "Civil Engineering"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Use YouTube embed URL"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
