# Generated by Django 4.2.16 on 2026-01-14 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="candidate_profile",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="interviewsession",
            name="intro_step",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="interview_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
