# Generated by Django 4.2.16 on 2026-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AI", "0002_interviewsession_candidate_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewsession",
            name="candidate_profile",
        ),
        migrations.RemoveField(
            model_name="interviewsession",
            name="intro_step",
        ),
        migrations.AlterField(
            model_name="interviewmessage",
            name="sender",
            field=models.CharField(
                choices=[("user", "User"), ("ai", "AI")], max_length=10
            ),
        ),
    ]
